In [1]:
import pandas as pd
import numpy as np

In [2]:
# main attribute is nd array

In [3]:
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a1.ndim

1

In [6]:
a2 = np.array([[1, 2, 3],
               [4, 5, 6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
type(a2), a2.ndim

(numpy.ndarray, 2)

In [8]:
a3 = np.array([[[1, 2, 3],
               [4, 5, 6]],
               [[1, 2, 3],
               [4, 5, 6]]])
type(a3), a3.ndim

(numpy.ndarray, 3)

In [9]:
a1.shape, a2.shape, a3.shape

((3,), (2, 3), (2, 2, 3))

In [10]:
# Create a dataframe from numpy array

df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

In [11]:
# Creating arrays

simple_array = np.array([1, 2, 3])
simple_array.dtype

dtype('int64')

In [12]:
ones = np.ones((2, 3), dtype = 'int64')
ones

array([[1, 1, 1],
       [1, 1, 1]])

In [13]:
zeros = np.zeros((3, 2), dtype = 'int64')
zeros

array([[0, 0],
       [0, 0],
       [0, 0]])

In [14]:
# start, stop, step
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [15]:
random_array = np.random.randint(0, 10, size = (3, 5))
random_array

array([[9, 2, 2, 5, 4],
       [1, 9, 9, 7, 1],
       [1, 0, 5, 7, 2]])

In [16]:
random_array_2 = np.random.random((3, 5))
random_array_2

array([[0.28813673, 0.99098494, 0.95531107, 0.43577517, 0.84225827],
       [0.2974656 , 0.24489983, 0.76393811, 0.14970525, 0.87784318],
       [0.83837602, 0.42324653, 0.62611791, 0.06945436, 0.15827123]])

In [17]:
random_array_3 = np.random.rand(3, 5)
random_array_3

array([[0.68962108, 0.75951242, 0.67380235, 0.78019136, 0.32413754],
       [0.50300867, 0.20670578, 0.81053469, 0.03929928, 0.43105987],
       [0.71333196, 0.29490453, 0.28866725, 0.28432762, 0.04324693]])

In [18]:
# Pseudo - Random numbers

np.random.seed(seed = 0)
random_array_4 = np.random.randint(10, size = (3, 5))
random_array_4

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1]])

In [19]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
a1[0]

1

In [21]:
a2[0]

array([1, 2, 3])

In [22]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
a3[:2, :2, :2]

array([[[1, 2],
        [4, 5]],

       [[1, 2],
        [4, 5]]])

In [24]:
a4 = np.random.randint(10, size = (2, 3, 4, 5))
a4

array([[[[6, 7, 7, 8, 1],
         [5, 9, 8, 9, 4],
         [3, 0, 3, 5, 0],
         [2, 3, 8, 1, 3]],

        [[3, 3, 7, 0, 1],
         [9, 9, 0, 4, 7],
         [3, 2, 7, 2, 0],
         [0, 4, 5, 5, 6]],

        [[8, 4, 1, 4, 9],
         [8, 1, 1, 7, 9],
         [9, 3, 6, 7, 2],
         [0, 3, 5, 9, 4]]],


       [[[4, 6, 4, 4, 3],
         [4, 4, 8, 4, 3],
         [7, 5, 5, 0, 1],
         [5, 9, 3, 0, 5]],

        [[0, 1, 2, 4, 2],
         [0, 3, 2, 0, 7],
         [5, 9, 0, 2, 7],
         [2, 9, 2, 3, 3]],

        [[2, 3, 4, 1, 2],
         [9, 1, 4, 6, 8],
         [2, 3, 0, 0, 6],
         [0, 6, 3, 3, 8]]]])

In [25]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [26]:
a4[:, :, :, :4]

array([[[[6, 7, 7, 8],
         [5, 9, 8, 9],
         [3, 0, 3, 5],
         [2, 3, 8, 1]],

        [[3, 3, 7, 0],
         [9, 9, 0, 4],
         [3, 2, 7, 2],
         [0, 4, 5, 5]],

        [[8, 4, 1, 4],
         [8, 1, 1, 7],
         [9, 3, 6, 7],
         [0, 3, 5, 9]]],


       [[[4, 6, 4, 4],
         [4, 4, 8, 4],
         [7, 5, 5, 0],
         [5, 9, 3, 0]],

        [[0, 1, 2, 4],
         [0, 3, 2, 0],
         [5, 9, 0, 2],
         [2, 9, 2, 3]],

        [[2, 3, 4, 1],
         [9, 1, 4, 6],
         [2, 3, 0, 0],
         [0, 6, 3, 3]]]])

In [27]:
# Aggregation in numpy

listy = [1, 2, 3]
sum(listy)

6

In [28]:
a1

array([1, 2, 3])

In [29]:
np.sum(a1)

6

In [30]:
massive_array = np.random.random(100000)

In [31]:
massive_array[:20]

array([0.16494046, 0.36980809, 0.14644176, 0.56961841, 0.70373728,
       0.28847644, 0.43328806, 0.75610669, 0.39609828, 0.89603839,
       0.63892108, 0.89155444, 0.68005557, 0.44919774, 0.97857093,
       0.11620191, 0.7670237 , 0.41182014, 0.67543908, 0.24979628])

In [32]:
%timeit sum(massive_array) # Python's inbuilt function

The slowest run took 4.31 times longer than the fastest. This could mean that an intermediate result is being cached.
19.9 ms ± 11.8 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [33]:
%timeit np.sum(massive_array) # Numpy's inbuilt function

43.9 µs ± 1.44 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [34]:
np.mean(a2)

3.5

In [35]:
np.min(a2), np.max(a2)

(1, 6)

In [36]:
np.std(a2)

1.707825127659933

In [37]:
np.var(a2)

2.9166666666666665

In [38]:
a2.shape

(2, 3)

In [39]:
a2.reshape((2,3,1))

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [40]:
a2_reshape = a2.reshape(2, 3, 1)

In [41]:
a2.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [45]:
# Dot product example

# Number of jars sold
sales_amounts = np.random.randint(20, size = (5, 3))

# Weekly sales data
weekly_sales = pd.DataFrame(sales_amounts, index = ["Mon", "Tue", "Wed", "Thu", "Fri"],
                            columns = ["Almond butter", "Peanut Butter", "Cashew Butter"])

weekly_sales

Almond butter  Peanut Butter  Cashew Butter
Mon             17              1              8
Tue              4             14              3
Wed              4             12              6
Thu             12             14             11
Fri             10             17             15

In [46]:
# Create prices array

prices = np.array([10, 8, 12])
prices

array([10,  8, 12])

In [49]:
# Create butter prices dataframe

butter_prices = pd.DataFrame(prices.reshape(1, 3),
                             index = ["Price"],
                             columns = ["Almond butter", "Peanut Butter", "Cashew Butter"])
butter_prices

Almond butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [53]:
# Shapes are not aligne, need to transpose

total_sales = prices.dot(sales_amounts.T)
total_sales

array([274, 188, 208, 364, 416])

In [54]:
weekly_sales["Total ($)"] = total_sales

In [55]:
weekly_sales

Almond butter  Peanut Butter  Cashew Butter  Total ($)
Mon             17              1              8        274
Tue              4             14              3        188
Wed              4             12              6        208
Thu             12             14             11        364
Fri             10             17             15        416

In [59]:
# Sorting arrays

random_array, np.sort(random_array)

(array([[9, 2, 2, 5, 4],
        [1, 9, 9, 7, 1],
        [1, 0, 5, 7, 2]]),
 array([[2, 2, 4, 5, 9],
        [1, 1, 7, 9, 9],
        [0, 1, 2, 5, 7]]))

In [67]:
%%html
<img src = "https://github.com/mrdbourke/zero-to-mastery-ml/blob/master/images/numpy-car-photo.png?raw=true"/>

In [69]:
# Turning images into numpy arrays

from matplotlib.image import imread

car = imread("/content/numpy-car-photo.png")
car

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]],

       [[0.44313726, 0.43529412, 0.40392157, 1.        ],
        [0.3137255 , 0.31764707, 0.27450982, 1.        ],
        [0.2       , 0.21176471, 0.14117648, 1.        ],
        ...,
        [0.5058824 , 0.5372549 , 0.4117647 , 1.        ],
        [0.49803922, 0.52156866, 0.39607844, 1.        ],
        [0.4       , 0.42745098, 0.34117648, 1.        ]],

       [[0.39607844, 0.38039216, 0.34117648, 1.        ],
        [0.31764707, 0.3137255 , 0.27450982, 1.        ],
        [0.28627452, 0.29411766, 0.24705882, 1.        ],
        ...,
        [0.44705883, 0.45882353, 0.32156864, 1.        ],
        [0.45882353, 0.482352

In [70]:
car.size, car.shape

(991300, (431, 575, 4))